development:
  cloud_name: msitbrasil
  api_key: '224195695462522'
  api_secret: VmfK4ppoLRuUO8-__31gIlEbINw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: msitbrasil
  api_key: '224195695462522'
  api_secret: VmfK4ppoLRuUO8-__31gIlEbINw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: msitbrasil
  api_key: '224195695462522'
  api_secret: VmfK4ppoLRuUO8-__31gIlEbINw
  enhance_image_tag: true
  static_image_support: false